<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="Query_COLLEQUITY" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ARIS-KPEI-PROJECT/OR11-eCLEARSCollateral/Query_COLLEQUITY" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/Query_COLLEQUITY" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ARIS-KPEI-PROJECT/OR11-eCLEARSCollateral/Query_COLLEQUITY" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
   <plt:partnerLinkType name="Query_COLLEQUITY_plt">
      <plt:role name="Query_COLLEQUITY_role">
         <plt:portType name="tns:Query_COLLEQUITY_ptt"/>
      </plt:role>
   </plt:partnerLinkType>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Query_COLLEQUITY" schemaLocation="xsd/Query_COLLEQUITY.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="Query_COLLEQUITYInput_msg">
      <wsdl:part name="Query_COLLEQUITYInput_msg" element="db:Query_COLLEQUITYInput"/>
   </wsdl:message>
   <wsdl:message name="Query_COLLEQUITYOutputCollection_msg">
      <wsdl:part name="Query_COLLEQUITYOutputCollection" element="db:Query_COLLEQUITYOutputCollection"/>
   </wsdl:message>
   <wsdl:portType name="Query_COLLEQUITY_ptt">
      <wsdl:operation name="Query_COLLEQUITY">
         <wsdl:input message="tns:Query_COLLEQUITYInput_msg"/>
         <wsdl:output message="tns:Query_COLLEQUITYOutputCollection_msg"/>
      </wsdl:operation>
   </wsdl:portType>
</wsdl:definitions>
