<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="TotalRow_COLLCASH" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ARIS-KPEI-PROJECT/OR11-eCLEARSCollateral/TotalRow_COLLCASH" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/TotalRow_COLLCASH" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ARIS-KPEI-PROJECT/OR11-eCLEARSCollateral/TotalRow_COLLCASH" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
   <plt:partnerLinkType name="TotalRow_COLLCASH_plt">
      <plt:role name="TotalRow_COLLCASH_role">
         <plt:portType name="tns:TotalRow_COLLCASH_ptt"/>
      </plt:role>
   </plt:partnerLinkType>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/TotalRow_COLLCASH" schemaLocation="xsd/TotalRow_COLLCASH.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="TotalRow_COLLCASHInput_msg">
      <wsdl:part name="TotalRow_COLLCASHInput_msg" element="db:TotalRow_COLLCASHInput"/>
   </wsdl:message>
   <wsdl:message name="TotalRow_COLLCASHOutput_msg">
      <wsdl:part name="TotalRow_COLLCASHOutput" element="db:TotalRow_COLLCASHOutput"/>
   </wsdl:message>
   <wsdl:portType name="TotalRow_COLLCASH_ptt">
      <wsdl:operation name="TotalRow_COLLCASH">
         <wsdl:input message="tns:TotalRow_COLLCASHInput_msg"/>
         <wsdl:output message="tns:TotalRow_COLLCASHOutput_msg"/>
      </wsdl:operation>
   </wsdl:portType>
</wsdl:definitions>
